# Generated by Django 4.1 on 2022-10-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_saham', models.TextField()),
                ('harga_saham', models.IntegerField(max_length=255)),
                ('risk', models.TextField()),
            ],
        ),
    ]
