# Generated by Django 4.1 on 2022-11-01 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_saham', models.CharField(default='ABCD', max_length=10)),
                ('nama_perusahaan', models.TextField(default='PT ABCD Tbk.')),
                ('harga_saham', models.IntegerField()),
                ('risk', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Saham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_saham', models.CharField(default='ABCD', max_length=10)),
                ('nama_perusahaan', models.TextField(default='PT ABCD Tbk.')),
                ('harga_saham', models.IntegerField()),
                ('risk', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.TextField(default='jangan monopoli saham yaa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
