# Generated by Django 4.1 on 2022-10-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_saham', models.CharField(default='ABCD', max_length=10)),
                ('nama_perusahaan', models.TextField(default='PT ABCD Tbk.')),
                ('harga_saham', models.IntegerField()),
                ('risk', models.CharField(max_length=10)),
            ],
        ),
    ]
