# Generated by Django 4.1 on 2022-10-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saham',
            name='harga_saham',
            field=models.IntegerField(),
        ),
    ]
