# Generated by Django 4.1 on 2022-11-01 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_saham_harga_saham'),
        ('stock', '0003_note'),
    ]

    operations = [
    ]
