# Generated by Django 4.1 on 2022-12-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestionbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='user',
        ),
    ]
