# Generated by Django 4.1 on 2022-11-01 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_crypto', models.TextField(default='ETHS', max_length=4)),
                ('nama_crypto', models.TextField(default='Ethnorium')),
                ('harga_crypto', models.IntegerField()),
                ('risk', models.TextField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='crypto',
            name='nama_crypto',
            field=models.TextField(default='Ethnorium'),
        ),
        migrations.AddField(
            model_name='crypto',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='kode_crypto',
            field=models.CharField(default='ETHS', max_length=4),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='risk',
            field=models.TextField(max_length=10),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(default='These are the notes for your crypto')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
